/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or
// formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SitemapDotxmlRouteImport } from "./routes/sitemap[.]xml";
import { Route as TermsAndConditionsRouteImport } from "./routes/terms-and-conditions";
import { Route as ServicesRouteImport } from "./routes/services";
import { Route as PrivacyPolicyRouteImport } from "./routes/privacy-policy";
import { Route as LocationsRouteImport } from "./routes/locations";
import { Route as ContactRouteImport } from "./routes/contact";
import { Route as AboutRouteImport } from "./routes/about";
import { Route as IndexRouteImport } from "./routes/index";

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: "/sitemap.xml",
  path: "/sitemap.xml",
  getParentRoute: () => rootRouteImport,
} as any);

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: "/terms-and-conditions",
  path: "/terms-and-conditions",
  getParentRoute: () => rootRouteImport,
} as any);

const ServicesRoute = ServicesRouteImport.update({
  id: "/services",
  path: "/services",
  getParentRoute: () => rootRouteImport,
} as any);

const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: "/privacy-policy",
  path: "/privacy-policy",
  getParentRoute: () => rootRouteImport,
} as any);

const LocationsRoute = LocationsRouteImport.update({
  id: "/locations",
  path: "/locations",
  getParentRoute: () => rootRouteImport,
} as any);

const ContactRoute = ContactRouteImport.update({
  id: "/contact",
  path: "/contact",
  getParentRoute: () => rootRouteImport,
} as any);

const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any);

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/contact": typeof ContactRoute;
  "/locations": typeof LocationsRoute;
  "/privacy-policy": typeof PrivacyPolicyRoute;
  "/services": typeof ServicesRoute;
  "/terms-and-conditions": typeof TermsAndConditionsRoute;
  "/sitemap.xml": typeof SitemapDotxmlRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/contact": typeof ContactRoute;
  "/locations": typeof LocationsRoute;
  "/privacy-policy": typeof PrivacyPolicyRoute;
  "/services": typeof ServicesRoute;
  "/terms-and-conditions": typeof TermsAndConditionsRoute;
  "/sitemap.xml": typeof SitemapDotxmlRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/contact": typeof ContactRoute;
  "/locations": typeof LocationsRoute;
  "/privacy-policy": typeof PrivacyPolicyRoute;
  "/services": typeof ServicesRoute;
  "/terms-and-conditions": typeof TermsAndConditionsRoute;
  "/sitemap.xml": typeof SitemapDotxmlRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;

  fullPaths:
    | "/"
    | "/about"
    | "/contact"
    | "/locations"
    | "/privacy-policy"
    | "/services"
    | "/terms-and-conditions"
    | "/sitemap.xml";

  fileRoutesByTo: FileRoutesByTo;

  to:
    | "/"
    | "/about"
    | "/contact"
    | "/locations"
    | "/privacy-policy"
    | "/services"
    | "/terms-and-conditions"
    | "/sitemap.xml";

  id:
    | "__root__"
    | "/"
    | "/about"
    | "/contact"
    | "/locations"
    | "/privacy-policy"
    | "/services"
    | "/terms-and-conditions"
    | "/sitemap.xml";

  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutRoute: typeof AboutRoute;
  ContactRoute: typeof ContactRoute;
  LocationsRoute: typeof LocationsRoute;
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute;
  ServicesRoute: typeof ServicesRoute;
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute;
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/sitemap.xml": {
      id: "/sitemap.xml";
      path: "/sitemap.xml";
      fullPath: "/sitemap.xml";
      preLoaderRoute: typeof SitemapDotxmlRouteImport;
      parentRoute: typeof rootRouteImport;
    };

    "/terms-and-conditions": {
      id: "/terms-and-conditions";
      path: "/terms-and-conditions";
      fullPath: "/terms-and-conditions";
      preLoaderRoute: typeof TermsAndConditionsRouteImport;
      parentRoute: typeof rootRouteImport;
    };

    "/services": {
      id: "/services";
      path: "/services";
      fullPath: "/services";
      preLoaderRoute: typeof ServicesRouteImport;
      parentRoute: typeof rootRouteImport;
    };

    "/privacy-policy": {
      id: "/privacy-policy";
      path: "/privacy-policy";
      fullPath: "/privacy-policy";
      preLoaderRoute: typeof PrivacyPolicyRouteImport;
      parentRoute: typeof rootRouteImport;
    };

    "/locations": {
      id: "/locations";
      path: "/locations";
      fullPath: "/locations";
      preLoaderRoute: typeof LocationsRouteImport;
      parentRoute: typeof rootRouteImport;
    };

    "/contact": {
      id: "/contact";
      path: "/contact";
      fullPath: "/contact";
      preLoaderRoute: typeof ContactRouteImport;
      parentRoute: typeof rootRouteImport;
    };

    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };

    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  AboutRoute,
  ContactRoute,
  LocationsRoute,
  PrivacyPolicyRoute,
  ServicesRoute,
  TermsAndConditionsRoute,
  SitemapDotxmlRoute,
};

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { startInstance } from "./start";

declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}